from django.shortcuts import render

# Create your views here.
def avereges(request):
    return render(request,'averages.html')
def course(request):
    return render(request,'course.html')
def timetable(request):
    return render(request,'timetable.html')
def seminar(request):
    return render(request,'seminar.html')
def institute(request):
    return render(request,'institute.html')
def anchortag(request):
    return render(request,'anchortag.html')
def background(request):
    return render(request,'background.html')
def box(request):
    return render(request,'box.html')
def buttons(request):
    return render(request,'buttons.html')
def calculator(request):
    return render(request,'calculator.html')
def csspositions(request):
    return render(request,'csspositions.html')
def register(request):
    return render(request,'register.html')
def semantic(request):
    return render(request,'semantic.html')
def semanticvideo(request):
    return render(request,'semanticvideo.html')
def student(request):
    return render(request,'student.html')
def textformating(request):
    return render(request,'textformating.html')
def translate(request):
    return render(request,'translate.html')
def movie(request):
    return render(request,'movie.html')
def emp(request):
    return render(request,'emp.html')
def rotate(request):
    return render(request,'rotate.html')
def zomato(request):
    return render(request,'zomato.html')